version: '3.4'

services:
  categorydb:
    container_name: appdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=6wuvirmipwpdd4qnu
      - POSTGRES_DB=CategoryDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  
  attributedb:
    container_name: appdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=3fndqf4awm
      - POSTGRES_DB=AttributeDb
    restart: always
    ports: 
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgreslq/data/

  redisdb:
    container_name: redisdb
    restart: always
    ports:
      - "6379:6379"
  
  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=ozcan.caparoglu@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=Capar.11
    restart: always
    ports:
        - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  categoryservice.api:
    container_name: categoryservice.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:CategoryConnectionString=Server=categorydb;Port=5432;Database=CategoryDb;User Id=admin;Password=6wuvirmipwpdd4qnu"
    depends_on:
      - categorydb
      - redisdb
    ports:
      - "8000:80"

  attributeservice.api:
    container_name: attributeservice.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:AttributeConnectionString=Server=attributedb;Port=5432;Database=AttributeDb;User Id=admin;Password=3fndqf4awm"
    ports:
      - "8001:80"

