version: '3.4'

services:
  appdb:
    image: postgres

  redisdb:
    image: redis:alpine

  pgadmin:
    image: dpage/pgadmin4

  categoryservice.api:
    image: ${DOCKER_REGISTRY-}categoryserviceapi
    build:
      context: .
      dockerfile: src/Infrastructure/CategoryService/CategoryService.Api/Dockerfile

  attributeservice.api:
    image: ${DOCKER_REGISTRY-}attributeserviceapi
    build:
      context: .
      dockerfile: src/Infrastructure/AttributeService/AttributeService.Api/Dockerfile

volumes:
  postgres_data:
  pgadmin_data:
